/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useCallback } from 'react';
import Sidebar from './components/Sidebar';
import Header from './components/Header';
import LiveMonitoring from './components/LiveMonitoring';
import AlertHistory from './components/AlertHistory';
import SensorHealth from './components/SensorHealth';
import SettingsPanel from './components/SettingsPanel';
import EmergencyModal from './components/EmergencyModal';
import ActiveAlertsList, { SimulationAlert } from './components/ActiveAlertsList';
import TelemetryDashboard from './components/TelemetryDashboard';
import SettingsDashboard from './components/SettingsDashboard';

import { StationData, SecurityAlert, SensorStatus, IntegrationConfig } from './types';
import { Activity, ShieldAlert, Radio, Settings as SettingsIcon } from 'lucide-react';

export default function App() {
  // Navigation State
  const [currentTab, setCurrentTab] = useState<string>('live');
  const [isEmergencyOpen, setIsEmergencyOpen] = useState<boolean>(false);

  // Dashboard view: 'normal' = all stations healthy; 'alarm' = st-4km floods
  const [dashboardView, setDashboardView] = useState<'normal' | 'alarm' | 'telemetry' | 'settings'>('normal');

  // Expanded card: null = grid view; stationId = single-card focus view
  const [expandedCardId, setExpandedCardId] = useState<string | null>(null);

  // Simulation engine active/inactive
  const [isSimulating, setIsSimulating] = useState(false);

  // Floating alert notifications generated by the simulation engine
  const [simulationAlerts, setSimulationAlerts] = useState<SimulationAlert[]>([]);

  // Configuration settings (for Java Spring integration)
  const [config, setConfig] = useState<IntegrationConfig>({
    useJavaApi: false,
    javaBaseUrl: 'http://localhost:8080/api/hydro-sentinel'
  });

  // Secondary Telemetry constants/state
  const [rainLevel, setRainLevel] = useState<number>(12); // mm/h
  const [basinSaturation, setBasinSaturation] = useState<number>(64.01); // %
  const [dischargeRate, setDischargeRate] = useState<number>(1.2); // k m³/s
  const [sensorHealth, setSensorHealth] = useState<number>(100); // %

  // Simulated Station State (matching core dashboard mock parameters)
  const [stations, setStations] = useState<StationData[]>([
    {
      id: 'st-5km',
      name: 'BASIN 5KM',
      distance: '5KM',
      level: 4.51,
      rateOfChange: 0.05,
      status: 'normal',
      imageUrl: '',
      history: [4.38, 4.41, 4.39, 4.42, 4.45, 4.43, 4.48, 4.51]
    },
    {
      id: 'st-4km',
      name: 'LIVE 4KM',
      distance: '4KM',
      level: 4.48,
      rateOfChange: 0.00,
      status: 'normal',
      imageUrl: '',
      history: [4.49, 4.48, 4.48, 4.47, 4.49, 4.48, 4.48, 4.48]
    },
    {
      id: 'st-3km',
      name: 'LIVE 3KM',
      distance: '3KM',
      level: 4.48,
      rateOfChange: 0.00,
      status: 'normal',
      imageUrl: '',
      history: [4.49, 4.48, 4.48, 4.47, 4.49, 4.48, 4.48, 4.48]
    },
    {
      id: 'st-2km',
      name: 'LIVE 2KM',
      distance: '2KM',
      level: 4.31,
      rateOfChange: -0.02,
      status: 'normal',
      imageUrl: '',
      history: [4.36, 4.35, 4.34, 4.35, 4.33, 4.32, 4.31, 4.31]
    },
    {
      id: 'st-1km',
      name: 'LIVE 1KM',
      distance: '1KM',
      level: 4.28,
      rateOfChange: 0.00,
      status: 'normal',
      imageUrl: '',
      history: [4.28, 4.28, 4.28, 4.28, 4.28, 4.28, 4.28, 4.28]
    }
  ]);

  // Simulated Alert Event Log (starts empty in normal mode)
  const [alerts, setAlerts] = useState<SecurityAlert[]>([]);

  // Simulated Sensor Statuses
  const [sensors, setSensors] = useState<SensorStatus[]>([
    { id: 'SEN-RAD-5KM', name: 'Ultrasonic Radar 5KM', type: ' ultrasonic radar RF', location: 'Upstream Basin Edge', status: 'online', uptime: 99.8, latency: 42, lastChecked: 'Just Now' },
    { id: 'SEN-RAD-4KM', name: 'Ultrasonic Radar 4KM', type: ' ultrasonic radar RF', location: 'Forest Bend Anchor', status: 'online', uptime: 99.9, latency: 45, lastChecked: 'Just Now' },
    { id: 'SEN-RAD-3KM', name: 'Ultrasonic Radar 3KM', type: ' high accuracy radar', location: 'Bridge Sluice Gate 3', status: 'online', uptime: 98.4, latency: 51, lastChecked: 'Just Now' },
    { id: 'SEN-RAD-2KM', name: 'Ultrasonic Radar 2KM', type: ' light wave radar', location: 'Canal Entrance Pylon', status: 'online', uptime: 99.6, latency: 38, lastChecked: 'Just Now' },
    { id: 'SEN-RAD-1KM', name: 'Ultrasonic Radar 1KM', type: ' acoustic wave sounder', location: 'Inlet Drain wall', status: 'online', uptime: 100.0, latency: 36, lastChecked: 'Just Now' },
    { id: 'SEN-PLU-01', name: 'Tipping-Bucket Pluviometer', type: ' rain precipitation collector', location: 'Command Hub Roof', status: 'online', uptime: 99.7, latency: 41, lastChecked: 'Just Now' },
    { id: 'SEN-SAT-01', name: 'Hydraulic saturation probe', type: ' soil moisture tester', location: 'Waterfall Ridge Slope', status: 'online', uptime: 99.2, latency: 48, lastChecked: 'Just Now' },
    { id: 'SEN-DIS-01', name: 'Doppler flow speed detector', type: ' microwave velocity radar', location: 'Primary Outflow Tunnel', status: 'online', uptime: 99.8, latency: 44, lastChecked: 'Just Now' },
  ]);

  // Start simulation: stagger alert notifications upstream → downstream with auto-redirect.
  const handleStartSimulation = useCallback(() => {
    setIsSimulating(true);
    const fmtTime = () => new Date().toLocaleTimeString();

    // Phase 1 — 5KM warning (immediate: furthest upstream detects rise first)
    setSimulationAlerts([
      {
        id: 'sim-1',
        stationId: 'st-5km',
        stationName: '5KM Monitoring Station',
        timestamp: fmtTime(),
        timeAgo: 'JUST NOW',
        severity: 'warning',
        title: '5KM Rising Rapidly',
        message:
          'Upstream accretion spike detected at basin inlet. Rate: +0.05m/min. Downstream stations on standby.',
        acknowledged: false,
      },
    ]);

    // Phase 2 — 3KM warning (2s later: surge propagates downstream)
    setTimeout(() => {
      setSimulationAlerts(prev => [
        ...prev,
        {
          id: 'sim-2',
          stationId: 'st-3km',
          stationName: '3KM Monitoring Station',
          timestamp: fmtTime(),
          timeAgo: 'JUST NOW',
          severity: 'warning',
          title: '3KM Rising Rapidly',
          message:
            'Flood surge propagating through floodplain. Rate: +0.12m/min. Gate interlocks on alert.',
          acknowledged: false,
        },
      ]);
    }, 2000);

    // Phase 3 — 4KM critical breach (5s total: surge reaches 4KM sluice gate)
    setTimeout(() => {
      setSimulationAlerts(prev => [
        ...prev,
        {
          id: 'sim-3',
          stationId: 'st-4km',
          stationName: '4KM Monitoring Station',
          timestamp: fmtTime(),
          timeAgo: 'JUST NOW',
          severity: 'critical',
          title: '4KM Station Critical Breach',
          message:
            'Water level exceeded critical threshold of 4.90m. Sluice interlock disengagement required. Immediate action!',
          acknowledged: false,
        },
      ]);
    }, 5000);

    // Phase 4 — auto-redirect to alarm dashboard (5s after critical = 10s total)
    setTimeout(() => {
      setDashboardView('alarm');
      setStations(prev =>
        prev.map(s =>
          s.id === 'st-4km'
            ? {
                ...s,
                name: 'ALERT 4KM',
                level: 5.12,
                rateOfChange: 0.12,
                status: 'alert' as const,
                history: [4.82, 4.89, 4.93, 4.98, 5.02, 5.05, 5.09, 5.12],
              }
            : s
        )
      );
      setAlerts([
        {
          id: 'AL-9204',
          stationId: 'st-4km',
          stationName: 'Station 4KM Upstream',
          timestamp: fmtTime().replace(/(\d+:\d+:\d+).*/, '$1'),
          level: 5.12,
          threshold: 5.0,
          status: 'active',
          severity: 'critical',
          details:
            'Abrupt water level increase (+0.12 m/min) detected. Sluice interlock disengagement recommended.',
        },
      ]);
      setExpandedCardId('st-4km');
    }, 10000);
  }, []);

  // Stop simulation: clear all floating alerts and return to normal view.
  const handleStopSimulation = useCallback(() => {
    setIsSimulating(false);
    setSimulationAlerts([]);
    setAlerts([]);
    setDashboardView('normal');
    setExpandedCardId(null);
    setStations(prev =>
      prev.map(s =>
        s.id === 'st-4km'
          ? {
              ...s,
              name: 'LIVE 4KM',
              level: 4.48,
              rateOfChange: 0.0,
              status: 'normal' as const,
              history: [4.49, 4.48, 4.48, 4.47, 4.49, 4.48, 4.48, 4.48],
            }
          : s
      )
    );
  }, []);

  // Clicking a floating alert notification → switch to alarm view.
  const handleSimAlertClick = useCallback(
    (stationId: string) => {
      if (dashboardView === 'normal') {
        setDashboardView('alarm');
        // Set st-4km into alert state.
        setStations(prev =>
          prev.map(s =>
            s.id === 'st-4km'
              ? {
                  ...s,
                  name: 'ALERT 4KM',
                  level: 5.12,
                  rateOfChange: 0.12,
                  status: 'alert' as const,
                  history: [4.82, 4.89, 4.93, 4.98, 5.02, 5.05, 5.09, 5.12],
                }
              : s
          )
        );
        setAlerts([
          {
            id: 'AL-9204',
            stationId: 'st-4km',
            stationName: 'Station 4KM Upstream',
            timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19),
            level: 5.12,
            threshold: 5.0,
            status: 'active',
            severity: 'critical',
            details:
              'Abrupt water level increase (+0.12 m/min) detected. Sluice interlock disengagement recommended.',
          },
        ]);
        setExpandedCardId('st-4km');
      }
    },
    [dashboardView]
  );

  // Acknowledge a single simulation alert.
  const handleAcknowledgeSimAlert = useCallback((id: string) => {
    setSimulationAlerts(prev =>
      prev.map(a => (a.id === id ? { ...a, acknowledged: true } : a))
    );
  }, []);

  // Toggle expanded card or trigger alarm transition.
  const handleCardClick = (stationId: string, _isAlert: boolean) => {
    // Card 3 (st-3km) in normal mode → switch to alarm and expand the alert card.
    if (stationId === 'st-3km' && dashboardView === 'normal') {
      setDashboardView('alarm');
      // Set st-4km into alert state.
      setStations(prev =>
        prev.map(s =>
          s.id === 'st-4km'
            ? {
                ...s,
                name: 'ALERT 4KM',
                level: 5.12,
                rateOfChange: 0.12,
                status: 'alert' as const,
                history: [4.82, 4.89, 4.93, 4.98, 5.02, 5.05, 5.09, 5.12],
              }
            : s
        )
      );
      // Create an active alert for the alarm station.
      setAlerts([
        {
          id: 'AL-9204',
          stationId: 'st-4km',
          stationName: 'Station 4KM Upstream',
          timestamp: new Date().toISOString().replace('T', ' ').slice(0, 19),
          level: 5.12,
          threshold: 5.0,
          status: 'active',
          severity: 'critical',
          details:
            'Abrupt water level increase (+0.12 m/min) detected across ultrasonic sensor arrays. Sluice interlock disengagement recommended.',
        },
      ]);
      setExpandedCardId('st-4km');
      return;
    }

    // Toggle expand/collapse for any card.
    setExpandedCardId(prev => (prev === stationId ? null : stationId));
  };

  // Action: Manual Gate Flush Simulation (Reduces Water Level)
  const handleFlushStation = (stationId: string) => {
    // Perform instant visual reduction in levels
    setStations(prevStations => 
      prevStations.map(station => {
        if (station.id === stationId) {
          const freshHistory = [...station.history];
          // Drop level by 0.85m to mimic flushing water
          const loweredLevel = Math.max(4.1, station.level - 0.85);
          freshHistory.shift();
          freshHistory.push(loweredLevel);

          return {
            ...station,
            level: loweredLevel,
            rateOfChange: -0.15, // now dropping
            status: 'normal',
            history: freshHistory
          };
        }
        return station;
      })
    );

    // Resolve any active alerts mapped to this station
    setAlerts(prevAlerts =>
      prevAlerts.map(alert => {
        if (alert.stationId === stationId && alert.status === 'active') {
          return { ...alert, status: 'resolved' as const };
        }
        return alert;
      })
    );

    // If flushing the alarm station (st-4km), return to normal dashboard view.
    if (stationId === 'st-4km' && dashboardView === 'alarm') {
      setDashboardView('normal');
      setExpandedCardId(null);
    }
  };

  // Action: Manually Resolve an active Alert from incident tracker
  const handleResolveAlert = (alertId: string) => {
    setAlerts(prevAlerts => 
      prevAlerts.map(alert => {
        if (alert.id === alertId) {
          // Find station id to flush it to normal ranges
          setTimeout(() => {
            handleFlushStation(alert.stationId);
          }, 300);

          return { ...alert, status: 'resolved' as const };
        }
        return alert;
      })
    );
  };

  // Reset entire simulation schema to catalog defaults
  const handleResetSimulation = () => {
    setDashboardView('normal');
    setExpandedCardId(null);
    setAlerts([]);
    setStations([
      {
        id: 'st-5km',
        name: 'BASIN 5KM',
        distance: '5KM',
        level: 4.51,
        rateOfChange: 0.05,
        status: 'normal',
        imageUrl: '',
        history: [4.38, 4.41, 4.39, 4.42, 4.45, 4.43, 4.48, 4.51]
      },
      {
        id: 'st-4km',
        name: 'LIVE 4KM',
        distance: '4KM',
        level: 4.48,
        rateOfChange: 0.00,
        status: 'normal',
        imageUrl: '',
        history: [4.49, 4.48, 4.48, 4.47, 4.49, 4.48, 4.48, 4.48]
      },
      {
        id: 'st-3km',
        name: 'LIVE 3KM',
        distance: '3KM',
        level: 4.48,
        rateOfChange: 0.00,
        status: 'normal',
        imageUrl: '',
        history: [4.49, 4.48, 4.48, 4.47, 4.49, 4.48, 4.48, 4.48]
      },
      {
        id: 'st-2km',
        name: 'LIVE 2KM',
        distance: '2KM',
        level: 4.31,
        rateOfChange: -0.02,
        status: 'normal',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBp5ZObaTwrmZzG_2ZT8_4MoQNJYy5bj80wpRW1mgeIbBPJ15vM9aDt-t3amTHl0mq1RN5_PG1WlDR6bUiQQeVChd54BFiSiIp9EXw-tTdjXshm3m9lacgGqqOPNJYy5bj80wpRW1mgeIbBPJ15vM9aDt-t3amTHl0mq1RN5_PG1WlDR6bUiQQeVChd54BFiSiIp9EXw-tTdjXshm3m9lacgGqqOPNWj4DHuGKXRosH9GRS79Vq9H0xD2cPirXq4_mNsKOZ29AwQ6IR9dRcLORFIZ43LNPzQClZec0i0z4j-OnuG1QbSqhYqxnpt0tZFk0vHp2CZJWipnIgl2kU9EfeRx9hmEsbiaC3ZZLP02VmdtSOkS',
        history: [4.36, 4.35, 4.34, 4.35, 4.33, 4.32, 4.31, 4.31]
      },
      {
        id: 'st-1km',
        name: 'LIVE 1KM',
        distance: '1KM',
        level: 4.28,
        rateOfChange: 0.00,
        status: 'normal',
        imageUrl: '',
        history: [4.28, 4.28, 4.28, 4.28, 4.28, 4.28, 4.28, 4.28]
      }
    ]);

    setRainLevel(12);
    setBasinSaturation(64.01);
    setDischargeRate(1.2);
    setSensorHealth(100);
  };

  // Manual diagnostics ping system calibration sweep
  const handleCalibrateSensor = (sensorId: string) => {
    setSensors(prev => 
      prev.map(s => {
        if (s.id === sensorId) {
          const freshTime = new Date().toLocaleTimeString();
          return {
            ...s,
            status: 'online',
            uptime: 99.9,
            latency: Math.floor(Math.random() * 15) + 30, // low latency on target
            lastChecked: `Calibrated at ${freshTime}`
          };
        }
        return s;
      })
    );
  };

  // Continuous physical telemetry simulation tick loop
  useEffect(() => {
    const interval = setInterval(() => {
      // 1. Gently fluctuate weather factors
      setRainLevel(prev => {
        const drift = (Math.random() - 0.5) * 0.4;
        return Math.max(0, Math.min(48, parseFloat((prev + drift).toFixed(1))));
      });

      setBasinSaturation(prev => {
        const delta = (Math.random() - 0.45) * 0.08; // slightly upwards
        return Math.max(10, Math.min(100, parseFloat((prev + delta).toFixed(2))));
      });

      setDischargeRate(prev => {
        const shift = (Math.random() - 0.5) * 0.05;
        return Math.max(0.1, Math.min(5.0, parseFloat((prev + shift).toFixed(2))));
      });

      // 2. Marginally drift station water levels
      setStations(prevStations =>
        prevStations.map(station => {
          // In alarm mode, all upstream stations rise (same river, flood propagates).
          // The alert station rises fastest. Other stations rise at reduced rates.
          const inAlarm = dashboardView === 'alarm';
          const isAlertStation = station.id === 'st-4km' && station.level >= 5.0;
          let delta = 0;

          if (isAlertStation) {
            // Alert station rises aggressively
            delta = (Math.random() - 0.3) * 0.015;
          } else if (inAlarm) {
            // All upstream stations also rise during flood, proportional to distance
            const upstreamFactor = station.id === 'st-5km' ? 0.7 : station.id === 'st-3km' ? 0.55 : station.id === 'st-2km' ? 0.35 : 0.2;
            delta = (Math.random() - 0.35) * 0.012 * upstreamFactor;
          } else {
            // Normal mode: gentle fluctuations around baseline
            delta = (Math.random() - 0.5) * 0.02;
          }

          const nextLevel = Math.max(3.8, parseFloat((station.level + delta).toFixed(2)));

          const updatedHistory = [...station.history];
          updatedHistory.shift();
          updatedHistory.push(nextLevel);

          const computedRate = delta * 4;

          return {
            ...station,
            level: nextLevel,
            rateOfChange: computedRate,
            history: updatedHistory,
          };
        })
      );
    }, 4500);

    return () => clearInterval(interval);
  }, [dashboardView]);

  const activeAlertsCount = alerts.filter(a => a.status === 'active').length;

  return (
    <div className="flex h-screen overflow-hidden bg-background text-on-surface select-none font-sans">
      
      {/* Side Navigation panel (Visible on Desktop) */}
      <Sidebar
        currentTab={currentTab}
        onChangeTab={setCurrentTab}
        onTriggerEmergency={() => setIsEmergencyOpen(true)}
        activeAlertsCount={activeAlertsCount}
        dashboardView={dashboardView}
        onSetDashboardView={setDashboardView}
      />

      {/* Main Content scope area */}
      <div className="flex-1 flex flex-col h-full overflow-hidden">

        {/* Floating simulation alert notifications */}
        <ActiveAlertsList
          alerts={simulationAlerts}
          onAcknowledge={handleAcknowledgeSimAlert}
          onAlertClick={handleSimAlertClick}
        />

        {/* Top Header status metrics */}
        <Header
          currentTab={currentTab}
          activeAlertsCount={activeAlertsCount}
          onClearAlerts={() => {
            setAlerts(prev => prev.map(a => ({ ...a, status: 'resolved' })));
          }}
          useJavaApi={config.useJavaApi}
          dashboardView={dashboardView}
          isSimulating={isSimulating}
          onStartSimulation={handleStartSimulation}
          onStopSimulation={handleStopSimulation}
        />

        {/* Dynamic Inner Tab Router */}
        <main className="flex-1 overflow-y-auto pb-20 md:pb-6">
          {/* Telemetry Dashboard — independent view, bypasses normal/alarm routing */}
          {dashboardView === 'telemetry' && (
            <div className="p-4 md:p-6">
              <TelemetryDashboard />
            </div>
          )}

          {/* Settings Dashboard — independent configuration view */}
          {dashboardView === 'settings' && <SettingsDashboard />}

          {dashboardView !== 'telemetry' && dashboardView !== 'settings' && currentTab === 'live' && (
            <LiveMonitoring
              stations={stations}
              onFlushStation={handleFlushStation}
              rainLevel={rainLevel}
              basinSaturation={basinSaturation}
              dischargeRate={dischargeRate}
              sensorHealth={sensorHealth}
              dashboardView={dashboardView}
              expandedCardId={expandedCardId}
              onCardClick={handleCardClick}
              isSimulating={isSimulating}
              onStartSimulation={handleStartSimulation}
              onStopSimulation={handleStopSimulation}
            />
          )}

          {currentTab === 'history' && (
            <AlertHistory 
              alerts={alerts} 
              onResolveAlert={handleResolveAlert}
              onRefresh={() => alert("Central Spring REST Alert catalog synchronized. Status 200 OK.")}
            />
          )}

          {currentTab === 'sensors' && (
            <SensorHealth 
              sensors={sensors}
              onCalibrateSensor={handleCalibrateSensor}
              onRefreshAll={() => {
                alert("Simulated API dispatch: Swept all 8 microwave, ultrasonic, and capacitive sensor arrays. Central registers indicate 100% cellular routing connectivity.");
              }}
              sensorHealthRatio={sensorHealth}
            />
          )}

          {currentTab === 'integration' && (
            <SettingsPanel 
              config={config} 
              onUpdateConfig={setConfig}
            />
          )}
        </main>

        {/* Bottom Navigation Hub (Visible on Mobile Only) */}
        <nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center h-16 bg-surface-container/90 backdrop-blur-lg border-t border-outline-variant/30 shadow-lg px-4">
          <button
            onClick={() => setCurrentTab('live')}
            className={`flex flex-col items-center justify-center p-2.5 transition-all ${
              currentTab === 'live' 
                ? 'text-secondary-container font-extrabold scale-105' 
                : 'text-on-surface-variant hover:text-white'
            }`}
          >
            <Activity size={18} />
            <span className="text-[9px] uppercase tracking-wider mt-0.5">Monitor</span>
          </button>
          
          <button
            onClick={() => setCurrentTab('history')}
            className={`flex flex-col items-center justify-center p-2.5 transition-all relative ${
              currentTab === 'history' 
                ? 'text-secondary-container font-extrabold scale-105' 
                : 'text-on-surface-variant hover:text-white'
            }`}
          >
            <ShieldAlert size={18} />
            <span className="text-[9px] uppercase tracking-wider mt-0.5">Alerts</span>
            {activeAlertsCount > 0 && (
              <span className="absolute top-2 right-4 w-1.5 h-1.5 bg-primary-container rounded-full animate-ping" />
            )}
          </button>

          <button
            onClick={() => setCurrentTab('sensors')}
            className={`flex flex-col items-center justify-center p-2.5 transition-all ${
              currentTab === 'sensors' 
                ? 'text-secondary-container font-extrabold scale-105' 
                : 'text-on-surface-variant hover:text-white'
            }`}
          >
            <Radio size={18} />
            <span className="text-[9px] uppercase tracking-wider mt-0.5">Sensors</span>
          </button>

          <button
            onClick={() => setCurrentTab('integration')}
            className={`flex flex-col items-center justify-center p-2.5 transition-all ${
              currentTab === 'integration' 
                ? 'text-secondary-container font-extrabold scale-105' 
                : 'text-on-surface-variant hover:text-white'
            }`}
          >
            <SettingsIcon size={18} />
            <span className="text-[9px] uppercase tracking-wider mt-0.5">Settings</span>
          </button>
        </nav>

      </div>

      {/* Auxiliary Global Emergency Modal drawer */}
      <EmergencyModal 
        isOpen={isEmergencyOpen} 
        onClose={() => setIsEmergencyOpen(false)} 
        stationsCount={stations.length}
      />

    </div>
  );
}
